In [ ]:
import pandas as pd

# Load all the datasets

## Task 1A

In [ ]:
github_link = "https://github.com/AridHasan/blp25_task1/blob/main/data/subtask_1A/"
raw_link = github_link.replace("blob/", "").replace("github.com", "raw.githubusercontent.com")

train_1A_df = pd.read_csv(raw_link+"blp25_hatespeech_subtask_1A_train.tsv", sep="\t", keep_default_na=False)
dev_1A_df = pd.read_csv(raw_link+"blp25_hatespeech_subtask_1A_dev.tsv", sep="\t", keep_default_na=False)
dev_test_1A_df = pd.read_csv(raw_link+"blp25_hatespeech_subtask_1A_dev_test_with_labels.tsv", sep="\t", keep_default_na=False)
test_1A_df = pd.read_csv(raw_link+"blp25_hatespeech_subtask_1A_test_with_labels.tsv", sep="\t", keep_default_na=False)

## Task 1B

In [ ]:
github_link = "https://github.com/AridHasan/blp25_task1/blob/main/data/subtask_1B/"
raw_link = github_link.replace("blob/", "").replace("github.com", "raw.githubusercontent.com")

train_1B_df = pd.read_csv(raw_link+"blp25_hatespeech_subtask_1B_train.tsv", sep="\t", keep_default_na=False)
dev_1B_df = pd.read_csv(raw_link+"blp25_hatespeech_subtask_1B_dev.tsv", sep="\t", keep_default_na=False)
dev_test_1B_df = pd.read_csv(raw_link+"blp25_hatespeech_subtask_1B_dev_test_with_labels.tsv", sep="\t", keep_default_na=False)
test_1B_df = pd.read_csv(raw_link+"blp25_hatespeech_subtask_1B_test_with_labels.tsv", sep="\t", keep_default_na=False)

## Task 1C

In [ ]:
github_link = "https://github.com/AridHasan/blp25_task1/blob/main/data/subtask_1C/"
raw_link = github_link.replace("blob/", "").replace("github.com", "raw.githubusercontent.com")

train_1C_df = pd.read_csv(raw_link+"blp25_hatespeech_subtask_1C_train.tsv", sep="\t", keep_default_na=False)
dev_1C_df = pd.read_csv(raw_link+"blp25_hatespeech_subtask_1C_dev.tsv", sep="\t", keep_default_na=False)
dev_test_1C_df = pd.read_csv(raw_link+"blp25_hatespeech_subtask_1C_dev_test_with_labels.tsv", sep="\t", keep_default_na=False)
test_1C_df = pd.read_csv(raw_link+"blp25_hatespeech_subtask_1C_test_with_labels.tsv", sep="\t", keep_default_na=False)

# Load Lematization Datasets

## BanglaLem
#### A Transformer-based Bangla Lemmatizer with an Enhanced Dataset
### https://www.sciencedirect.com/science/article/pii/S2772941925000626
### Dataset: https://docs.google.com/spreadsheets/d/1pR2bR0n-x9z_mHxNWiUJI-8NgzTV8ZTc5trGMoI-U3k/edit?pli=1&gid=1732451193

In [ ]:
import pandas as pd

google_sheet_url = "https://docs.google.com/spreadsheets/d/1pR2bR0n-x9z_mHxNWiUJI-8NgzTV8ZTc5trGMoI-U3k/edit?pli=1&gid=1732451193"
# Construct the direct download URL for the CSV format using output=csv
csv_export_url = google_sheet_url.replace("/edit?pli=1", "/export?format=csv&gid=1732451193")


try:
    bangla_lem_df = pd.read_csv(csv_export_url)
    # Remove the 'Unnamed: 0' column
    if 'Unnamed: 0' in bangla_lem_df.columns:
        bangla_lem_df = bangla_lem_df.drop('Unnamed: 0', axis=1)
    print("Successfully loaded the dataset:")
    display(bangla_lem_df.head())
except Exception as e:
    print(f"Error loading the dataset: {e}")

Successfully loaded the dataset:

  Inflected_Word    Lemma
0          সরাইও      সরা
1          সস্তা    সস্তা
2          কলহকে      কলহ
3           মেজর     মেজর
4        উত্যক্ত  উত্যক্ত

In [ ]:
bangla_lem_df

      Inflected_Word    Lemma
0              সরাইও      সরা
1              সস্তা    সস্তা
2              কলহকে      কলহ
3               মেজর     মেজর
4            উত্যক্ত  উত্যক্ত
...              ...      ...
96035         তেলুগু   তেলুগু
96036       রোজগারের   রোজগার
96037            পেই      পেই
96038       ইরানীদের    ইরানী
96039         লগ্নির    লগ্নি

[96040 rows x 2 columns]

## BaNeL
#### An encoder-decoder based Bangla neural lemmatizer
### https://link.springer.com/article/10.1007/s42452-022-04985-2
### Dataset: https://github.com/cseduashraful/BaNeL-Dataset/blob/main/bangla_lemmatization_dataset_BaNeL.xlsx

In [ ]:
import pandas as pd

github_excel_url = "https://github.com/cseduashraful/BaNeL-Dataset/blob/main/bangla_lemmatization_dataset_BaNeL.xlsx"
# Construct the raw GitHub URL
raw_excel_url = github_excel_url.replace("blob/", "").replace("github.com", "raw.githubusercontent.com")

try:
    banel_df = pd.read_excel(raw_excel_url)
    # Remove the 'POS' column if it exists
    if 'POS' in banel_df.columns:
        banel_df = banel_df.drop('POS', axis=1)
    print("Successfully loaded the dataset:")
    display(banel_df.head())
except Exception as e:
    print(f"Error loading the dataset: {e}")

Successfully loaded the dataset:

  Inflected_Word Lemma
0           কালে   কাল
1          কালের   কাল
2           কালই   কাল
3          কালটা   কাল
4        কালটাতে   কাল

In [ ]:
banel_df

      Inflected_Word    Lemma
0               কালে      কাল
1              কালের      কাল
2               কালই      কাল
3              কালটা      কাল
4            কালটাতে      কাল
...              ...      ...
22348           রোষে      রোষ
22349        উন্মোচন  উন্মোচন
22350          ঘিয়ের       ঘি
22351              ম        ম
22352           পূজো     পূজো

[22353 rows x 2 columns]

# Load Stopwords

## https://github.com/stopwords-iso/stopwords-bn/blob/master/stopwords-bn.txt

In [ ]:
import requests

stopwords_url = "https://raw.githubusercontent.com/stopwords-iso/stopwords-bn/master/stopwords-bn.txt"

try:
    response = requests.get(stopwords_url)
    response.raise_for_status() # Raise an HTTPError for bad responses (4xx or 5xx)
    stopwords_iso = response.text.splitlines()
    print("Successfully loaded stopwords from stopwords-bn.txt:")
    print(f"Number of stopwords: {len(stopwords_iso)}")
    print("First 10 stopwords:", stopwords_iso[:10])
except requests.exceptions.RequestException as e:
    print(f"Error loading stopwords from {stopwords_url}: {e}")
    stopwords_iso = [] # Initialize as empty list in case of error

Successfully loaded stopwords from stopwords-bn.txt:
Number of stopwords: 398
First 10 stopwords: ['অতএব', 'অথচ', 'অথবা', 'অনুযায়ী', 'অনেক', 'অনেকে', 'অনেকেই', 'অন্তত', 'অন্য', 'অবধি']

In [ ]:
stopwords_iso

['অতএব',
 'অথচ',
 'অথবা',
 'অনুযায়ী',
 'অনেক',
 'অনেকে',
 'অনেকেই',
 'অন্তত',
 'অন্য',
 'অবধি',
 'অবশ্য',
 'অর্থাত',
 'আই',
 'আগামী',
 'আগে',
 'আগেই',
 'আছে',
 'আজ',
 'আদ্যভাগে',
 'আপনার',
 'আপনি',
 'আবার',
 'আমরা',
 'আমাকে',
 'আমাদের',
 'আমার',
 'আমি',
 'আর',
 'আরও',
 'ই',
 'ইত্যাদি',
 'ইহা',
 'উচিত',
 'উত্তর',
 'উনি',
 'উপর',
 'উপরে',
 'এ',
 'এঁদের',
 'এঁরা',
 'এই',
 'একই',
 'একটি',
 'একবার',
 'একে',
 'এক্',
 'এখন',
 'এখনও',
 'এখানে',
 'এখানেই',
 'এটা',
 'এটাই',
 'এটি',
 'এত',
 'এতটাই',
 'এতে',
 'এদের',
 'এব',
 'এবং',
 'এবার',
 'এমন',
 'এমনকী',
 'এমনি',
 'এর',
 'এরা',
 'এল',
 'এস',
 'এসে',
 'ঐ',
 'ও',
 'ওঁদের',
 'ওঁর',
 'ওঁরা',
 'ওই',
 'ওকে',
 'ওখানে',
 'ওদের',
 'ওর',
 'ওরা',
 'কখনও',
 'কত',
 'কবে',
 'কমনে',
 'কয়েক',
 'কয়েকটি',
 'করছে',
 'করছেন',
 'করতে',
 'করবে',
 'করবেন',
 'করলে',
 'করলেন',
 'করা',
 'করাই',
 'করায়',
 'করার',
 'করি',
 'করিতে',
 'করিয়া',
 'করিয়ে',
 'করে',
 'করেই',
 'করেছিলেন',
 'করেছে',
 'করেছেন',
 'করেন',
 'কাউকে',
 'কাছ',
 'কাছে',
 'কাজ',
 'কাজে',
 'কারও',
 'কারণ',
 'কি',
 'কিংবা',
 'কিছু',
 'কিছুই',
 'কিন্তু',
 'কী',
 'কে',
 'কেউ',
 'কেউই',
 'কেখা',
 'কেন',
 'কোটি',
 'কোন',
 'কোনও',
 'কোনো',
 'ক্ষেত্রে',
 'কয়েক',
 'খুব',
 'গিয়ে',
 'গিয়েছে',
 'গিয়ে',
 'গুলি',
 'গেছে',
 'গেল',
 'গেলে',
 'গোটা',
 'চলে',
 'চান',
 'চায়',
 'চার',
 'চালু',
 'চেয়ে',
 'চেষ্টা',
 'ছাড়া',
 'ছাড়াও',
 'ছিল',
 'ছিলেন',
 'জন',
 'জনকে',
 'জনের',
 'জন্য',
 'জন্যওজে',
 'জানতে',
 'জানা',
 'জানানো',
 'জানায়',
 'জানিয়ে',
 'জানিয়েছে',
 'জে',
 'জ্নজন',
 'টি',
 'ঠিক',
 'তখন',
 'তত',
 'তথা',
 'তবু',
 'তবে',
 'তা',
 'তাঁকে',
 'তাঁদের',
 'তাঁর',
 'তাঁরা',
 'তাঁাহারা',
 'তাই',
 'তাও',
 'তাকে',
 'তাতে',
 'তাদের',
 'তার',
 'তারপর',
 'তারা',
 'তারৈ',
 'তাহলে',
 'তাহা',
 'তাহাতে',
 'তাহার',
 'তিনঐ',
 'তিনি',
 'তিনিও',
 'তুমি',
 'তুলে',
 'তেমন',
 'তো',
 'তোমার',
 'থাকবে',
 'থাকবেন',
 'থাকা',
 'থাকায়',
 'থাকে',
 'থাকেন',
 'থেকে',
 'থেকেই',
 'থেকেও',
 'দিকে',
 'দিতে',
 'দিন',
 'দিয়ে',
 'দিয়েছে',
 'দিয়েছেন',
 'দিলেন',
 'দু',
 'দুই',
 'দুটি',
 'দুটো',
 'দেওয়া',
 'দেওয়ার',
 'দেওয়া',
 'দেখতে',
 'দেখা',
 'দেখে',
 'দেন',
 'দেয়',
 'দ্বারা',
 'ধরা',
 'ধরে',
 'ধামার',
 'নতুন',
 'নয়',
 'না',
 'নাই',
 'নাকি',
 'নাগাদ',
 'নানা',
 'নিজে',
 'নিজেই',
 'নিজেদের',
 'নিজের',
 'নিতে',
 'নিয়ে',
 'নিয়ে',
 'নেই',
 'নেওয়া',
 'নেওয়ার',
 'নেওয়া',
 'নয়',
 'পক্ষে',
 'পর',
 'পরে',
 'পরেই',
 'পরেও',
 'পর্যন্ত',
 'পাওয়া',
 'পাচ',
 'পারি',
 'পারে',
 'পারেন',
 'পি',
 'পেয়ে',
 'পেয়্র্',
 'প্রতি',
 'প্রথম',
 'প্রভৃতি',
 'প্রযন্ত',
 'প্রাথমিক',
 'প্রায়',
 'প্রায়',
 'ফলে',
 'ফিরে',
 'ফের',
 'বক্তব্য',
 'বদলে',
 'বন',
 'বরং',
 'বলতে',
 'বলল',
 'বললেন',
 'বলা',
 'বলে',
 'বলেছেন',
 'বলেন',
 'বসে',
 'বহু',
 'বা',
 'বাদে',
 'বার',
 'বি',
 'বিনা',
 'বিভিন্ন',
 'বিশেষ',
 'বিষয়টি',
 'বেশ',
 'বেশি',
 'ব্যবহার',
 'ব্যাপারে',
 'ভাবে',
 'ভাবেই',
 'মতো',
 'মতোই',
 'মধ্যভাগে',
 'মধ্যে',
 'মধ্যেই',
 'মধ্যেও',
 'মনে',
 'মাত্র',
 'মাধ্যমে',
 'মোট',
 'মোটেই',
 'যখন',
 'যত',
 'যতটা',
 'যথেষ্ট',
 'যদি',
 'যদিও',
 'যা',
 'যাঁর',
 'যাঁরা',
 'যাওয়া',
 'যাওয়ার',
 'যাওয়া',
 'যাকে',
 'যাচ্ছে',
 'যাতে',
 'যাদের',
 'যান',
 'যাবে',
 'যায়',
 'যার',
 'যারা',
 'যিনি',
 'যে',
 'যেখানে',
 'যেতে',
 'যেন',
 'যেমন',
 'র',
 'রকম',
 'রয়েছে',
 'রাখা',
 'রেখে',
 'লক্ষ',
 'শুধু',
 'শুরু',
 'সঙ্গে',
 'সঙ্গেও',
 'সব',
 'সবার',
 'সমস্ত',
 'সম্প্রতি',
 'সহ',
 'সহিত',
 'সাধারণ',
 'সামনে',
 'সি',
 'সুতরাং',
 'সে',
 'সেই',
 'সেখান',
 'সেখানে',
 'সেটা',
 'সেটাই',
 'সেটাও',
 'সেটি',
 'স্পষ্ট',
 'স্বয়ং',
 'হইতে',
 'হইবে',
 'হইয়া',
 'হওয়া',
 'হওয়ায়',
 'হওয়ার',
 'হচ্ছে',
 'হত',
 'হতে',
 'হতেই',
 'হন',
 'হবে',
 'হবেন',
 'হয়',
 'হয়তো',
 'হয়নি',
 'হয়ে',
 'হয়েই',
 'হয়েছিল',
 'হয়েছে',
 'হয়েছেন',
 'হল',
 'হলে',
 'হলেই',
 'হলেও',
 'হলো',
 'হাজার',
 'হিসাবে',
 'হৈলে',
 'হোক',
 'হয়']

## https://www.kaggle.com/datasets/nuhashafnan/bangla-stopwords

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("nuhashafnan/bangla-stopwords")

print("Path to dataset files:", path)

Downloading from https://www.kaggle.com/api/v1/datasets/download/nuhashafnan/bangla-stopwords?dataset_version_number=1...

100%|██████████| 11.2k/11.2k [00:00<00:00, 13.3MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/nuhashafnan/bangla-stopwords/versions/1

In [ ]:
# Load the stopwords from the Excel file (assuming the stopwords are in the first column)
stopwords_df = pd.read_excel(path+"/stopwords_bangla.xlsx", header=1) # Assuming header is in the second row
# Assuming stopwords are in the second column, convert it to a list
stopwords_kaggle = stopwords_df.iloc[:, 1].tolist() # Extracting from the second column

In [ ]:
print("\nSuccessfully loaded stopwords from the zip file:")
print(f"Number of stopwords: {len(stopwords_kaggle)}")
print("First 10 stopwords:", stopwords_kaggle[:10])

Successfully loaded stopwords from the zip file:
Number of stopwords: 731
First 10 stopwords: ['অগত্যা', 'অত: পর', 'অতএব', 'অথচ', 'অথবা', 'অধিক', 'অধীনে', 'অধ্যায়', 'অনুগ্রহ', 'অনুভূত']

In [ ]:
stopwords_kaggle

['অগত্যা',
 'অত: পর',
 'অতএব',
 'অথচ',
 'অথবা',
 'অধিক',
 'অধীনে',
 'অধ্যায়',
 'অনুগ্রহ',
 'অনুভূত',
 'অনুযায়ী',
 'অনুরূপ',
 'অনুসন্ধান',
 'অনুসরণ',
 'অনুসারে',
 'অনুসৃত',
 'অনেক',
 'অনেকে',
 'অনেকেই',
 'অন্তত',
 'অন্য',
 'অন্যত্র',
 'অন্যভাবে',
 'অন্যান্য',
 'অপেক্ষাকৃতভাবে',
 'অবধি',
 'অবশ্য',
 'অবশ্যই',
 'অবস্থা',
 'অবিলম্বে',
 'অভ্যন্তরস্থ',
 'অর্জিত',
 'অর্থাত',
 'অসদৃশ',
 'অসম্ভাব্য',
 'আইন',
 'আউট',
 'আক্রান্ত',
 'আগামী',
 'আগে',
 'আগেই',
 'আগ্রহী',
 'আছে',
 'আজ',
 'আট',
 'আদেশ',
 'আদ্যভাগে',
 'আন্দাজ',
 'আপনার',
 'আপনি',
 'আবার',
 'আমরা',
 'আমাকে',
 'আমাদিগের',
 'আমাদের',
 'আমার',
 'আমি',
 'আর',
 'আরও',
 'আশি',
 'আশু',
 'আসা',
 'আসে',
 'ই',
 'ইচ্ছা',
 'ইচ্ছাপূর্বক',
 'ইতিমধ্যে',
 'ইতোমধ্যে',
 'ইত্যাদি',
 'ইশারা',
 'ইহা',
 'ইহাতে',
 'উক্তি',
 'উচিত',
 'উচ্চ',
 'উঠা',
 'উত্তম',
 'উত্তর',
 'উনি',
 'উপর',
 'উপরে',
 'উপলব্ধ',
 'উপায়',
 'উভয়',
 'উল্লেখ',
 'উল্লেখযোগ্যভাবে',
 'উহার',
 'ঊর্ধ্বতন',
 'এ',
 'এপর্যন্ত',
 'এঁদের',
 'এঁরা',
 'এই',
 'এইগুলো',
 'এইভাবে',
 'এক',
 'একই',
 'একটি',
 'একদা',
 'একবার',
 'একভাবে',
 'একরকম',
 'একসঙ্গে',
 'একা',
 'একে',
 'এক্',
 'এখন',
 'এখনও',
 'এখনো',
 'এখানে',
 'এখানেই',
 'এছাড়াও',
 'এটা',
 'এটাই',
 'এটি',
 'এত',
 'এতটাই',
 'এতদ্বারা',
 'এতে',
 'এদিকে',
 'এদের',
 'এপর্যন্ত',
 'এবং',
 'এবার',
 'এমন',
 'এমনকি',
 'এমনকী',
 'এমনি',
 'এর',
 'এরকম',
 'এরা',
 'এল',
 'এলাকায়',
 'এলাকার',
 'এস',
 'এসে',
 'ঐ',
 'ও',
 'ওঁদের',
 'ওঁর',
 'ওঁরা',
 'ওই',
 'ওকে',
 'ওখানে',
 'ওদের',
 'ওর',
 'ওরা',
 'ওহে',
 'কক্ষ',
 'কখন',
 'কখনও',
 'কত',
 'কবে',
 'কম',
 'কমনে',
 'কয়েক',
 'কয়েকটি',
 'করছে',
 'করছেন',
 'করতে',
 'করবে',
 'করবেন',
 'করলে',
 'করলেন',
 'করলো',
 'করা',
 'করাই',
 'করাত',
 'করার',
 'করায়',
 'করি',
 'করিতে',
 'করিয়া',
 'করিয়ে',
 'করে',
 'করেই',
 'করেছিল',
 'করেছিলেন',
 'করেছে',
 'করেছেন',
 'করেন',
 'কর্তব্য',
 'কাউকে',
 'কাছ',
 'কাছাকাছি',
 'কাছে',
 'কাজ',
 'কাজে',
 'কারও',
 'কারণ',
 'কারণসমূহ',
 'কারো',
 'কি',
 'কিংবা',
 'কিছু',
 'কিছুই',
 'কিছুটা',
 'কিছুনা',
 'কিনা',
 'কিন্তু',
 'কিভাবে',
 'কী',
 'কূপ',
 'কে',
 'কেউ',
 'কেউই',
 'কেউনা',
 'কেখা',
 'কেন',
 'কেবল',
 'কেবা',
 'কেস',
 'কেহ',
 'কোটি',
 'কোথা',
 'কোথাও',
 'কোথায়',
 'কোন',
 'কোনও',
 'কোনো',
 'ক্রম',
 'ক্ষেত্রে',
 'কয়েক',
 'কয়েকটি',
 'খুঁজছেন',
 'খুব',
 'খোলা',
 'খোলে',
 'গড়',
 'গত',
 'গিয়ে',
 'গিয়েছিলাম',
 'গিয়েছে',
 'গিয়ে',
 'গিয়েছে',
 'গুরুত্ব',
 'গুলি',
 'গেছে',
 'গেল',
 'গেলে',
 'গোটা',
 'গোষ্ঠীবদ্ধ',
 'গ্রহণ',
 'গ্রুপ',
 'ঘর',
 'ঘোষণা',
 'চলে',
 'চান',
 'চায়',
 'চার',
 'চালা',
 'চালান',
 'চালু',
 'চায়',
 'চেয়ে',
 'চেয়েছিলেন',
 'চেষ্টা',
 'চেয়ে',
 'ছয়',
 'ছাড়া',
 'ছাড়াছাড়ি',
 'ছাড়া',
 'ছাড়াও',
 'ছিল',
 'ছিলেন',
 'ছোট',
 'জন',
 'জনকে',
 'জনাব',
 'জনাবা',
 'জনের',
 'জন্য',
 'জানতাম',
 'জানতে',
 'জানা',
 'জানানো',
 'জানায়',
 'জানিয়ে',
 'জানিয়েছে',
 'জানে',
 'জায়গা',
 'জিজ্ঞাসা',
 'জিজ্ঞেস',
 'জিনিস',
 'জে',
 'জ্নজন',
 'টা',
 'টি',
 'ঠিক',
 'ঠিকআছে',
 'ডগা',
 'তখন',
 'তত',
 'তত্কারণে',
 'তত্প্রতি',
 'তথা',
 'তদনুসারে',
 'তদ্ব্যতীত',
 'তন্নতন্ন',
 'তবু',
 'তবে',
 'তরুণ',
 'তা',
 'তাঁকে',
 'তাঁদের',
 'তাঁর',
 'তাঁরা',
 'তাঁহারা',
 'তাই',
 'তাও',
 'তাকে',
 'তাতে',
 'তাদের',
 'তার',
 'তারপর',
 'তারপরেও',
 'তারা',
 'তারিখ',
 'তারৈ',
 'তাহলে',
 'তাহা',
 'তাহাতে',
 'তাহাদিগকে',
 'তাহাদেরই',
 'তাহার',
 'তিন',
 'তিনি',
 'তিনিও',
 'তীক্ষ্ন',
 'তুমি',
 'তুলে',
 'তেমন',
 'তৈরীর',
 'তো',
 'তোমার',
 'তোলে',
 'থাকবে',
 'থাকবেন',
 'থাকা',
 'থাকায়',
 'থাকায়',
 'থাকে',
 'থাকেন',
 'থেকে',
 'থেকেই',
 'থেকেও',
 'দরকারী',
 'দলবদ্ধ',
 'দান',
 'দিকে',
 'দিতে',
 'দিন',
 'দিয়ে',
 'দিয়েছে',
 'দিয়েছেন',
 'দিলেন',
 'দিয়ে',
 'দিয়েছে',
 'দিয়েছেন',
 'দু',
 'দুই',
 'দুটি',
 'দুটো',
 'দূরে',
 'দেওয়ার',
 'দেওয়া',
 'দেওয়ার',
 'দেখতে',
 'দেখা',
 'দেখাচ্ছে',
 'দেখিয়েছেন',
 'দেখে',
 'দেখেন',
 'দেন',
 'দেয়',
 'দেয়',
 'দ্বারা',
 'দ্বিগুণ',
 'দ্বিতীয়',
 'দ্য',
 'ধরা',
 'ধরে',
 'ধামার',
 'নতুন',
 'নব্বই',
 'নয়',
 'নাই',
 'নাকি',
 'নাগাদ',
 'নানা',
 'নাম',
 'নিচে',
 'নিছক',
 'নিজে',
 'নিজেই',
 'নিজেকে',
 'নিজেদের',
 'নিজেদেরকে',
 'নিজের',
 'নিতে',
 'নিদিষ্ট',
 'নিম্নাভিমুখে',
 'নিয়ে',
 'নির্দিষ্ট',
 'নির্বিশেষে',
 'নিশ্চিত',
 'নিয়ে',
 'নেই',
 'নেওয়ার',
 'নেওয়া',
 'নেয়ার',
 'নয়',
 'পক্ষই',
 'পক্ষে',
 'পঞ্চম',
 'পড়া',
 'পণ্য',
 'পথ',
 'পয়েন্ট',
 'পর',
 'পরন্তু',
 'পরবর্তী',
 'পরিণত',
 'পরিবর্তে',
 'পরে',
 'পরেই',
 'পরেও',
 'পর্যন্ত',
 'পর্যাপ্ত',
 'পাঁচ',
 'পাওয়া',
 'পাচ',
 'পায়',
 'পারা',
 'পারি',
 'পারিনি',
 'পারে',
 'পারেন',
 'পালা',
 'পাশ',
 'পাশে',
 'পিছনে',
 'পিঠের',
 'পুরোনো',
 'পুরোপুরি',
 'পূর্বে',
 'পৃষ্ঠা',
 'পৃষ্ঠাগুলি',
 'পেছনে',
 'পেয়েছেন',
 'পেয়ে',
 'পেয়্র্',
 'প্রকৃতপক্ষে',
 'প্রণীত',
 'প্রতি',
 'প্রথম',
 'প্রদত্ত',
 'প্রদর্শনী',
 'প্রদর্শিত',
 'প্রধানত',
 'প্রবলভাবে',
 'প্রভৃতি',
 'প্রমাণীকরণ',
 'প্রযন্ত',
 'প্রয়োজন',
 'প্রয়োজনীয়',
 'প্রসূত',
 'প্রাক্তন',
 'প্রাথমিক',
 'প্রাথমিকভাবে',
 'প্রান্ত',
 'প্রাপ্ত',
 'প্রায়',
 'প্রায়ই',
 'প্রায়',
 'ফলাফল',
 'ফলে',
 'ফিক্স',
 'ফিরে',
 'ফের',
 'বক্তব্য',
 'বছর',
 'বড়',
 'বদলে',
 'বন',
 'বন্ধ',
 'বরং',
 'বরাবর',
 'বর্ণন',
 'বর্তমান',
 'বলতে',
 'বলল',
 'বললেন',
 'বলা',
 'বলে',
 'বলেছেন',
 'বলেন',
 'বসে',
 'বহু',
 'বা',
 'বাঁক',
 'বাইরে',
 'বাকি',
 'বাড়ি',
 'বাতিক',
 'বাদ',
 'বাদে',
 'বার',
 'বাহিরে',
 'বিনা',
 'বিন্দু',
 'বিভিন্ন',
 'বিশেষ',
 'বিশেষণ',
 'বিশেষত',
 'বিশেষভাবে',
 'বিশ্ব',
 'বিষয়টি',
 'বুঝিয়ে',
 'বৃহত্তর',
 'বের',
 'বেশ',
 'বেশি',
 'বেশী',
 'ব্যতীত',
 'ব্যবহার',
 'ব্যবহারসমূহ',
 'ব্যবহৃত',
 'ব্যাক',
 'ব্যাপকভাবে',
 'ব্যাপারে',
 'ভবিষ্যতে',
 'ভান',
 'ভাবে',
 'ভাবেই',
 'ভাল',
 'ভিতরে',
 'ভিন্ন',
 'ভিন্নভাবে',
 'মত',
 'মতো',
 'মতোই',
 'মধ্যভাগে',
 'মধ্যে',
 'মধ্যেই',
 'মধ্যেও',
 'মনে',
 'মনে হয়',
 'মস্ত',
 'মহান',
 'মাত্র',
 'মাধ্যম',
 'মাধ্যমে',
 'মান',
 'মানানসই',
 'মানুষ',
 'মানে',
 'মামলা',
 'মিলিয়ন',
 'মুখ',
 'মূলত',
 'মোট',
 'মোটেই',
 'যখন',
 'যখনই',
 'যত',
 'যতটা',
 'যথা',
 'যথাক্রমে',
 'যথেষ্ট',
 'যদি',
 'যদিও',
 'যন্ত্রাংশ',
 'যা',
 'যাঁর',
 'যাঁরা',
 'যাই',
 'যাওয়া',
 'যাওয়ার',
 'যাওয়া',
 'যাওয়ার',
 'যাকে',
 'যাচ্ছে',
 'যাতে',
 'যাদের',
 'যান',
 'যাবে',
 'যায়',
 'যার',
 'যারা',
 'যাহার',
 'যাহোক',
 'যিনি',
 'যে',
 'যেখানে',
 'যেখানেই',
 'যেটি',
 'যেতে',
 'যেন',
 'যেমন',
 'যেহেতু',
 'যোগ',
 'রকম',
 'রয়েছে',
 'রাখা',
 'রাখে',
 'রাজী',
 'রাজ্যের',
 'রেখে',
 'রয়েছে',
 'লক্ষ',
 'লাইন',
 'লাল',
 'শত',
 'শব্দ',
 'শীঘ্র',
 'শীঘ্রই',
 'শুধু',
 'শুরু',
 'শুরুতে',
 'শূন্য',
 'শেষ',
 'সংক্রান্ত',
 'সংক্ষিপ্ত',
 'সংক্ষেপে',
 'সংখ্যা',
 'সংখ্যার',
 'সংশ্লিষ্ট',
 'সক্ষম',
 'সঙ্গে',
 'সঙ্গেও',
 'সত্য',
 'সত্যিই',
 'সদয়',
 'সদস্য',
 'সদস্যদের',
 'সফলভাবে',
 'সব',
 'সবচেয়ে',
 'সবাই',
 'সবার',
 'সময়',
 'সমস্ত',
 'সমান',
 'সম্পন্ন',
 'সম্প্রতি',
 'সম্ভব',
 'সম্ভবত',
 'সম্ভাব্য',
 'সরাইয়া',
 'সর্বত্র',
 'সর্বদা',
 'সর্বস্বান্ত',
 'সহ',
 'সহিত',
 'সাত',
 'সাধারণ',
 'সাধারণত',
 'সাব',
 'সাবেক',
 'সামগ্রিক',
 'সামনে',
 'সামান্য',
 'সাম্প্রতিক',
 'সুতরাং',
 'সুত্র',
 'সূচক',
 'সে',
 'সে হবে',
 'সেই',
 'সেকেন্ড',
 'সেখান',
 'সেখানে',
 'সেগুলো',
 'সেটা',
 'সেটাই',
 'সেটাও',
 'সেটি',
 'সেরা',
 'স্টপ',
 'স্থাপিত',
 'স্পষ্ট',
 'স্পষ্টত',
 'স্পষ্টতই',
 'স্ব',
 'স্বয়ং',
 'স্বাগত',
 'স্বাভাবিকভাবে',
 'স্বার্থ',
 'স্বয়ং',
 'হইতে',
 'হইবে',
 'হইয়া',
 'হওয়া',
 'হওয়ায়',
 'হওয়ার',
 'হচ্ছে',
 'হত',
 'হতে',
 'হতেই',
 'হন',
 'হবে',
 'হবেন',
 'হয়',
 'হয়তো',
 'হয়নি',
 'হয়ে',
 'হয়েই',
 'হয়েছিল',
 'হয়েছে',
 'হয়েছেন',
 'হল',
 'হলে',
 'হলেই',
 'হলেও',
 'হলো',
 'হাজার',
 'হায়',
 'হারানো',
 'হিসাবে',
 'হৈলে',
 'হোক',
 'হয়',
 'হয়তো',
 'হয়নি',
 'হয়ে',
 'হয়েই',
 'হয়েছিল',
 'হয়েছে',
 'হয়েছেন',
 'অংশ']

## https://www.ranks.nl/stopwords/bengali

In [ ]:
stopwords_ranks_text = """অবশ্য
অনেক
অনেকে
অনেকেই
অন্তত
অথবা
অথচ
অর্থাত
অন্য
আজ
আছে
আপনার
আপনি
আবার
আমরা
আমাকে
আমাদের
আমার
আমি
আরও
আর
আগে
আগেই
আই
অতএব
আগামী
অবধি
অনুযায়ী
আদ্যভাগে
এই
একই
একে
একটি
এখন
এখনও
এখানে
এখানেই
এটি
এটা
এটাই
এতটাই
এবং
একবার
এবার
এদের
এঁদের
এমন
এমনকী
এল
এর
এরা
এঁরা
এস
এত
এতে
এসে
একে
এ
ঐ
 ই
ইহা
ইত্যাদি
উনি
উপর
উপরে
উচিত
ও
ওই
ওর
ওরা
ওঁর
ওঁরা
ওকে
ওদের
ওঁদের
ওখানে
কত
কবে
করতে
কয়েক
কয়েকটি
করবে
করলেন
করার
কারও
করা
করি
করিয়ে
করার
করাই
করলে
করলেন
করিতে
করিয়া
করেছিলেন
করছে
করছেন
করেছেন
করেছে
করেন
করবেন
করায়
করে
করেই
কাছ
কাছে
কাজে
কারণ
কিছু
কিছুই
কিন্তু
কিংবা
কি
কী
কেউ
কেউই
কাউকে
কেন
কে
কোনও
কোনো
কোন
কখনও
ক্ষেত্রে
খুব     গুলি
গিয়ে
গিয়েছে
গেছে
গেল
গেলে
গোটা
চলে
ছাড়া
ছাড়াও
ছিলেন
ছিল
জন্য
জানা
ঠিক
তিনি
তিনঐ
তিনিও
তখন
তবে
তবু
তাঁদের
তাঁাহারা
তাঁরা
তাঁর
তাঁকে
তাই
তেমন
তাকে
তাহা
তাহাতে
তাহার
তাদের
তারপর
তারা
তারৈ
তার
তাহলে
তিনি
তা
তাও
তাতে
তো
তত
তুমি
তোমার
তথা
থাকে
থাকা
থাকায়
থেকে
থেকেও
থাকবে
থাকেন
থাকবেন
থেকেই
দিকে
দিতে
দিয়ে
দিয়েছে
দিয়েছেন
দিলেন
দু
দুটি
দুটো
দেয়
দেওয়া
দেওয়ার
দেখা
দেখে
দেখতে
দ্বারা
ধরে
ধরা
নয়
নানা
না
নাকি
নাগাদ
নিতে
নিজে
নিজেই
নিজের
নিজেদের
নিয়ে
নেওয়া
নেওয়ার
নেই
নাই
পক্ষে
পর্যন্ত
পাওয়া
পারেন
পারি
পারে
পরে
পরেই
পরেও
পর
পেয়ে
প্রতি
প্রভৃতি
প্রায়
ফের
ফলে
ফিরে
ব্যবহার
বলতে
বললেন
বলেছেন
বলল
বলা
বলেন
বলে
বহু
বসে
বার
বা
বিনা
বরং
বদলে
বাদে
বার
বিশেষ
বিভিন্ন বিষয়টি
ব্যবহার
ব্যাপারে
ভাবে
ভাবেই
মধ্যে
মধ্যেই
মধ্যেও
মধ্যভাগে
মাধ্যমে
মাত্র
মতো
মতোই
মোটেই
যখন
যদি
যদিও
যাবে
যায়
যাকে
যাওয়া
যাওয়ার
যত
যতটা
যা
যার
যারা
যাঁর
যাঁরা
যাদের
যান
যাচ্ছে
যেতে
যাতে
যেন
যেমন
যেখানে
যিনি
যে
রেখে
রাখা
রয়েছে
রকম
শুধু
সঙ্গে
সঙ্গেও
সমস্ত
সব
সবার
সহ
সুতরাং
সহিত
সেই
সেটা
সেটি
সেটাই
সেটাও
সম্প্রতি
সেখান
সেখানে
সে
স্পষ্ট
স্বয়ং
হইতে
হইবে
হৈলে
হইয়া
হচ্ছে
হত
হতে
হতেই
হবে
হবেন
হয়েছিল
হয়েছে
হয়েছেন
হয়ে
হয়নি
হয়
হয়েই
হয়তো
হল
হলে
হলেই
হলেও
হলো
হিসাবে
হওয়া
হওয়ার
হওয়ায়
হন
হোক
জন
জনকে
জনের
জানতে
জানায়
জানিয়ে
জানানো
জানিয়েছে
জন্য
জন্যওজে
জে
বেশ
দেন
তুলে
ছিলেন
চান
চায়
চেয়ে
মোট
যথেষ্ট
টি"""

stopwords_ranks = [word.strip() for word in stopwords_ranks_text.splitlines() if word.strip()]

file_path = "stopwords_ranks.txt"
with open(file_path, "w", encoding="utf-8") as f:
    for word in stopwords_ranks:
        f.write(word + "\n")

print(f"Stopwords saved to {file_path}")
print(f"Number of stopwords saved: {len(stopwords_ranks)}")

Stopwords saved to stopwords_ranks.txt
Number of stopwords saved: 361

In [ ]:
stopwords_ranks

['অবশ্য',
 'অনেক',
 'অনেকে',
 'অনেকেই',
 'অন্তত',
 'অথবা',
 'অথচ',
 'অর্থাত',
 'অন্য',
 'আজ',
 'আছে',
 'আপনার',
 'আপনি',
 'আবার',
 'আমরা',
 'আমাকে',
 'আমাদের',
 'আমার',
 'আমি',
 'আরও',
 'আর',
 'আগে',
 'আগেই',
 'আই',
 'অতএব',
 'আগামী',
 'অবধি',
 'অনুযায়ী',
 'আদ্যভাগে',
 'এই',
 'একই',
 'একে',
 'একটি',
 'এখন',
 'এখনও',
 'এখানে',
 'এখানেই',
 'এটি',
 'এটা',
 'এটাই',
 'এতটাই',
 'এবং',
 'একবার',
 'এবার',
 'এদের',
 'এঁদের',
 'এমন',
 'এমনকী',
 'এল',
 'এর',
 'এরা',
 'এঁরা',
 'এস',
 'এত',
 'এতে',
 'এসে',
 'একে',
 'এ',
 'ঐ',
 'ই',
 'ইহা',
 'ইত্যাদি',
 'উনি',
 'উপর',
 'উপরে',
 'উচিত',
 'ও',
 'ওই',
 'ওর',
 'ওরা',
 'ওঁর',
 'ওঁরা',
 'ওকে',
 'ওদের',
 'ওঁদের',
 'ওখানে',
 'কত',
 'কবে',
 'করতে',
 'কয়েক',
 'কয়েকটি',
 'করবে',
 'করলেন',
 'করার',
 'কারও',
 'করা',
 'করি',
 'করিয়ে',
 'করার',
 'করাই',
 'করলে',
 'করলেন',
 'করিতে',
 'করিয়া',
 'করেছিলেন',
 'করছে',
 'করছেন',
 'করেছেন',
 'করেছে',
 'করেন',
 'করবেন',
 'করায়',
 'করে',
 'করেই',
 'কাছ',
 'কাছে',
 'কাজে',
 'কারণ',
 'কিছু',
 'কিছুই',
 'কিন্তু',
 'কিংবা',
 'কি',
 'কী',
 'কেউ',
 'কেউই',
 'কাউকে',
 'কেন',
 'কে',
 'কোনও',
 'কোনো',
 'কোন',
 'কখনও',
 'ক্ষেত্রে',
 'খুব     গুলি',
 'গিয়ে',
 'গিয়েছে',
 'গেছে',
 'গেল',
 'গেলে',
 'গোটা',
 'চলে',
 'ছাড়া',
 'ছাড়াও',
 'ছিলেন',
 'ছিল',
 'জন্য',
 'জানা',
 'ঠিক',
 'তিনি',
 'তিনঐ',
 'তিনিও',
 'তখন',
 'তবে',
 'তবু',
 'তাঁদের',
 'তাঁাহারা',
 'তাঁরা',
 'তাঁর',
 'তাঁকে',
 'তাই',
 'তেমন',
 'তাকে',
 'তাহা',
 'তাহাতে',
 'তাহার',
 'তাদের',
 'তারপর',
 'তারা',
 'তারৈ',
 'তার',
 'তাহলে',
 'তিনি',
 'তা',
 'তাও',
 'তাতে',
 'তো',
 'তত',
 'তুমি',
 'তোমার',
 'তথা',
 'থাকে',
 'থাকা',
 'থাকায়',
 'থেকে',
 'থেকেও',
 'থাকবে',
 'থাকেন',
 'থাকবেন',
 'থেকেই',
 'দিকে',
 'দিতে',
 'দিয়ে',
 'দিয়েছে',
 'দিয়েছেন',
 'দিলেন',
 'দু',
 'দুটি',
 'দুটো',
 'দেয়',
 'দেওয়া',
 'দেওয়ার',
 'দেখা',
 'দেখে',
 'দেখতে',
 'দ্বারা',
 'ধরে',
 'ধরা',
 'নয়',
 'নানা',
 'না',
 'নাকি',
 'নাগাদ',
 'নিতে',
 'নিজে',
 'নিজেই',
 'নিজের',
 'নিজেদের',
 'নিয়ে',
 'নেওয়া',
 'নেওয়ার',
 'নেই',
 'নাই',
 'পক্ষে',
 'পর্যন্ত',
 'পাওয়া',
 'পারেন',
 'পারি',
 'পারে',
 'পরে',
 'পরেই',
 'পরেও',
 'পর',
 'পেয়ে',
 'প্রতি',
 'প্রভৃতি',
 'প্রায়',
 'ফের',
 'ফলে',
 'ফিরে',
 'ব্যবহার',
 'বলতে',
 'বললেন',
 'বলেছেন',
 'বলল',
 'বলা',
 'বলেন',
 'বলে',
 'বহু',
 'বসে',
 'বার',
 'বা',
 'বিনা',
 'বরং',
 'বদলে',
 'বাদে',
 'বার',
 'বিশেষ',
 'বিভিন্ন বিষয়টি',
 'ব্যবহার',
 'ব্যাপারে',
 'ভাবে',
 'ভাবেই',
 'মধ্যে',
 'মধ্যেই',
 'মধ্যেও',
 'মধ্যভাগে',
 'মাধ্যমে',
 'মাত্র',
 'মতো',
 'মতোই',
 'মোটেই',
 'যখন',
 'যদি',
 'যদিও',
 'যাবে',
 'যায়',
 'যাকে',
 'যাওয়া',
 'যাওয়ার',
 'যত',
 'যতটা',
 'যা',
 'যার',
 'যারা',
 'যাঁর',
 'যাঁরা',
 'যাদের',
 'যান',
 'যাচ্ছে',
 'যেতে',
 'যাতে',
 'যেন',
 'যেমন',
 'যেখানে',
 'যিনি',
 'যে',
 'রেখে',
 'রাখা',
 'রয়েছে',
 'রকম',
 'শুধু',
 'সঙ্গে',
 'সঙ্গেও',
 'সমস্ত',
 'সব',
 'সবার',
 'সহ',
 'সুতরাং',
 'সহিত',
 'সেই',
 'সেটা',
 'সেটি',
 'সেটাই',
 'সেটাও',
 'সম্প্রতি',
 'সেখান',
 'সেখানে',
 'সে',
 'স্পষ্ট',
 'স্বয়ং',
 'হইতে',
 'হইবে',
 'হৈলে',
 'হইয়া',
 'হচ্ছে',
 'হত',
 'হতে',
 'হতেই',
 'হবে',
 'হবেন',
 'হয়েছিল',
 'হয়েছে',
 'হয়েছেন',
 'হয়ে',
 'হয়নি',
 'হয়',
 'হয়েই',
 'হয়তো',
 'হল',
 'হলে',
 'হলেই',
 'হলেও',
 'হলো',
 'হিসাবে',
 'হওয়া',
 'হওয়ার',
 'হওয়ায়',
 'হন',
 'হোক',
 'জন',
 'জনকে',
 'জনের',
 'জানতে',
 'জানায়',
 'জানিয়ে',
 'জানানো',
 'জানিয়েছে',
 'জন্য',
 'জন্যওজে',
 'জে',
 'বেশ',
 'দেন',
 'তুলে',
 'ছিলেন',
 'চান',
 'চায়',
 'চেয়ে',
 'মোট',
 'যথেষ্ট',
 'টি']

## https://github.com/eftekhar-hossain/Bengali-Restaurant-Reviews/blob/master/Dataset%20and%20Code/stopwords-bn.txt

In [ ]:
import requests

stopwords_url_eftekhar = "https://raw.githubusercontent.com/eftekhar-hossain/Bengali-Restaurant-Reviews/master/Dataset%20and%20Code/stopwords-bn.txt"

try:
    response = requests.get(stopwords_url_eftekhar)
    response.raise_for_status() # Raise an HTTPError for bad responses (4xx or 5xx)
    stopwords_eftekhar = response.text.splitlines()
    # Clean up leading/trailing whitespace and empty lines
    stopwords_eftekhar = [word.strip() for word in stopwords_eftekhar if word.strip()]
    print("Successfully loaded stopwords from eftekhar-hossain/stopwords-bn.txt:")
    print(f"Number of stopwords: {len(stopwords_eftekhar)}")
    print("First 10 stopwords:", stopwords_eftekhar[:10])
except requests.exceptions.RequestException as e:
    print(f"Error loading stopwords from {stopwords_url_eftekhar}: {e}")
    stopwords_eftekhar = [] # Initialize as empty list in case of error

Successfully loaded stopwords from eftekhar-hossain/stopwords-bn.txt:
Number of stopwords: 387
First 10 stopwords: ['অতএব', 'অথচ', 'অথবা', 'অনুযায়ী', 'অনেক', 'অনেকে', 'অনেকেই', 'অন্তত', 'অন্য', 'অবধি']

In [ ]:
stopwords_eftekhar

['অতএব',
 'অথচ',
 'অথবা',
 'অনুযায়ী',
 'অনেক',
 'অনেকে',
 'অনেকেই',
 'অন্তত',
 'অন্য',
 'অবধি',
 'অবশ্য',
 'অর্থাত',
 'আই',
 'আগামী',
 'আগে',
 'আগেই',
 'আছে',
 'আজ',
 'আদ্যভাগে',
 'আপনার',
 'আপনি',
 'আবার',
 'আমরা',
 'আমাকে',
 'আমাদের',
 'আমার',
 'আমি',
 'আর',
 'আরও',
 'ই',
 'ইত্যাদি',
 'ইহা',
 'উচিত',
 'উত্তর',
 'উনি',
 'উপর',
 'উপরে',
 'এ',
 'এঁদের',
 'এঁরা',
 'এই',
 'একই',
 'একটি',
 'একবার',
 'একে',
 'এক্',
 'এখন',
 'এখনও',
 'এখানে',
 'এখানেই',
 'এটা',
 'এটাই',
 'এটি',
 'এত',
 'এতটাই',
 'এতে',
 'এদের',
 'এব',
 'এবং',
 'এবার',
 'এমন',
 'এমনকী',
 'এমনি',
 'এর',
 'এরা',
 'এল',
 'এস',
 'এসে',
 'ঐ',
 'ও',
 'ওঁদের',
 'ওঁর',
 'ওঁরা',
 'ওই',
 'ওকে',
 'ওখানে',
 'ওদের',
 'ওর',
 'ওরা',
 'কখনও',
 'কত',
 'কবে',
 'কমনে',
 'কয়েক',
 'কয়েকটি',
 'করছে',
 'করছেন',
 'করতে',
 'করবে',
 'করবেন',
 'করলে',
 'করলেন',
 'করা',
 'করাই',
 'করায়',
 'করার',
 'করি',
 'করিতে',
 'করিয়া',
 'করিয়ে',
 'করে',
 'করেই',
 'করেছিলেন',
 'করেছে',
 'করেছেন',
 'করেন',
 'কাউকে',
 'কাছ',
 'কাছে',
 'কাজ',
 'কাজে',
 'কারও',
 'কারণ',
 'কি',
 'কিংবা',
 'কিছু',
 'কিছুই',
 'কিন্তু',
 'কী',
 'কে',
 'কেউ',
 'কেউই',
 'কেখা',
 'কেন',
 'কোটি',
 'কোন',
 'কোনও',
 'কোনো',
 'ক্ষেত্রে',
 'কয়েক',
 'খুব',
 'গিয়ে',
 'গিয়েছে',
 'গিয়ে',
 'গুলি',
 'গেছে',
 'গেল',
 'গেলে',
 'গোটা',
 'চলে',
 'চান',
 'চায়',
 'চার',
 'চালু',
 'চেয়ে',
 'ছাড়া',
 'ছাড়াও',
 'ছিল',
 'ছিলেন',
 'জন',
 'জনকে',
 'জনের',
 'জন্য',
 'জন্যওজে',
 'জানতে',
 'জানা',
 'জানানো',
 'জানায়',
 'জানিয়ে',
 'জানিয়েছে',
 'জে',
 'জ্নজন',
 'টি',
 'তখন',
 'তত',
 'তথা',
 'তবু',
 'তবে',
 'তা',
 'তাঁকে',
 'তাঁদের',
 'তাঁর',
 'তাঁরা',
 'তাঁাহারা',
 'তাই',
 'তাও',
 'তাকে',
 'তাতে',
 'তাদের',
 'তার',
 'তারপর',
 'তারা',
 'তারৈ',
 'তাহলে',
 'তাহা',
 'তাহাতে',
 'তাহার',
 'তিনঐ',
 'তিনি',
 'তিনিও',
 'তুমি',
 'তুলে',
 'তেমন',
 'তো',
 'তোমার',
 'থাকবে',
 'থাকবেন',
 'থাকা',
 'থাকায়',
 'থাকে',
 'থাকেন',
 'থেকে',
 'থেকেই',
 'থেকেও',
 'দিকে',
 'দিতে',
 'দিন',
 'দিয়ে',
 'দিয়েছে',
 'দিয়েছেন',
 'দিলেন',
 'দু',
 'দুই',
 'দুটি',
 'দুটো',
 'দেওয়া',
 'দেওয়ার',
 'দেওয়া',
 'দেখতে',
 'দেখা',
 'দেখে',
 'দেন',
 'দেয়',
 'দ্বারা',
 'ধরা',
 'ধরে',
 'ধামার',
 'নতুন',
 'নাকি',
 'নাগাদ',
 'নানা',
 'নিজে',
 'নিজেই',
 'নিজেদের',
 'নিজের',
 'নিতে',
 'নিয়ে',
 'নিয়ে',
 'নেওয়া',
 'নেওয়ার',
 'নেওয়া',
 'পক্ষে',
 'পর',
 'পরে',
 'পরেই',
 'পরেও',
 'পর্যন্ত',
 'পাওয়া',
 'পাচ',
 'পারি',
 'পারে',
 'পারেন',
 'পি',
 'পেয়ে',
 'পেয়্র্',
 'প্রতি',
 'প্রথম',
 'প্রভৃতি',
 'প্রযন্ত',
 'প্রাথমিক',
 'প্রায়',
 'প্রায়',
 'ফলে',
 'ফিরে',
 'ফের',
 'বক্তব্য',
 'বদলে',
 'বন',
 'বরং',
 'বলতে',
 'বলল',
 'বললেন',
 'বলা',
 'বলে',
 'বলেছেন',
 'বলেন',
 'বসে',
 'বহু',
 'বা',
 'বাদে',
 'বার',
 'বি',
 'বিনা',
 'বিভিন্ন',
 'বিষয়টি',
 'বেশ',
 'ব্যবহার',
 'ব্যাপারে',
 'ভাবে',
 'ভাবেই',
 'মতো',
 'মতোই',
 'মধ্যভাগে',
 'মধ্যে',
 'মধ্যেই',
 'মধ্যেও',
 'মনে',
 'মাত্র',
 'মাধ্যমে',
 'মোট',
 'মোটেই',
 'যখন',
 'যত',
 'যতটা',
 'যদি',
 'যদিও',
 'যা',
 'যাঁর',
 'যাঁরা',
 'যাওয়া',
 'যাওয়ার',
 'যাওয়া',
 'যাকে',
 'যাচ্ছে',
 'যাতে',
 'যাদের',
 'যান',
 'যাবে',
 'যায়',
 'যার',
 'যারা',
 'যিনি',
 'যে',
 'যেখানে',
 'যেতে',
 'যেন',
 'যেমন',
 'র',
 'রকম',
 'রয়েছে',
 'রাখা',
 'রেখে',
 'লক্ষ',
 'শুরু',
 'সঙ্গে',
 'সঙ্গেও',
 'সব',
 'সবার',
 'সমস্ত',
 'সম্প্রতি',
 'সহ',
 'সহিত',
 'সাধারণ',
 'সামনে',
 'সি',
 'সুতরাং',
 'সে',
 'সেই',
 'সেখান',
 'সেখানে',
 'সেটা',
 'সেটাই',
 'সেটাও',
 'সেটি',
 'স্পষ্ট',
 'স্বয়ং',
 'হইতে',
 'হইবে',
 'হইয়া',
 'হওয়া',
 'হওয়ায়',
 'হওয়ার',
 'হচ্ছে',
 'হত',
 'হতে',
 'হতেই',
 'হন',
 'হবে',
 'হবেন',
 'হয়',
 'হয়তো',
 'হয়নি',
 'হয়ে',
 'হয়েই',
 'হয়েছিল',
 'হয়েছে',
 'হয়েছেন',
 'হল',
 'হলে',
 'হলেই',
 'হলেও',
 'হলো',
 'হাজার',
 'হিসাবে',
 'হৈলে',
 'হোক',
 'হয়']

# Text Preprocessing

## Number removal (NR)

In [ ]:
import re

# Function to remove numbers
def remove_numbers(text):
    return re.sub(r'\d+', '', text)

# Apply number removal to all relevant text columns
train_1A_df['nr_text'] = train_1A_df['text'].apply(remove_numbers)
dev_1A_df['nr_text'] = dev_1A_df['text'].apply(remove_numbers)
dev_test_1A_df['nr_text'] = dev_test_1A_df['text'].apply(remove_numbers)
test_1A_df['nr_text'] = test_1A_df['text'].apply(remove_numbers)

train_1B_df['nr_text'] = train_1B_df['text'].apply(remove_numbers)
dev_1B_df['nr_text'] = dev_1B_df['text'].apply(remove_numbers)
dev_test_1B_df['nr_text'] = dev_test_1B_df['text'].apply(remove_numbers)
test_1B_df['nr_text'] = test_1B_df['text'].apply(remove_numbers)

train_1C_df['nr_text'] = train_1C_df['text'].apply(remove_numbers)
dev_1C_df['nr_text'] = dev_1C_df['text'].apply(remove_numbers)
dev_test_1C_df['nr_text'] = dev_test_1C_df['text'].apply(remove_numbers)
test_1C_df['nr_text'] = test_1C_df['text'].apply(remove_numbers)

print("Numbers removed from text columns in all datasets.")

Numbers removed from text columns in all datasets.

## Tokenization

In [ ]:
# Function for tokenization
def tokenize_text(text):
    return text.split()

# Apply tokenization to all relevant text columns
train_1A_df['t_text'] = train_1A_df['nr_text'].apply(tokenize_text)
dev_1A_df['t_text'] = dev_1A_df['nr_text'].apply(tokenize_text)
dev_test_1A_df['t_text'] = dev_test_1A_df['nr_text'].apply(tokenize_text)
test_1A_df['t_text'] = test_1A_df['nr_text'].apply(tokenize_text)

train_1B_df['t_text'] = train_1B_df['nr_text'].apply(tokenize_text)
dev_1B_df['t_text'] = dev_1B_df['nr_text'].apply(tokenize_text)
dev_test_1B_df['t_text'] = dev_test_1B_df['nr_text'].apply(tokenize_text)
test_1B_df['t_text'] = test_1B_df['nr_text'].apply(tokenize_text)

train_1C_df['t_text'] = train_1C_df['nr_text'].apply(tokenize_text)
dev_1C_df['t_text'] = dev_1C_df['nr_text'].apply(tokenize_text)
dev_test_1C_df['t_text'] = dev_test_1C_df['nr_text'].apply(tokenize_text)
test_1C_df['t_text'] = test_1C_df['nr_text'].apply(tokenize_text)

print("Text columns tokenized in all datasets.")

Text columns tokenized in all datasets.

## Lemmatization

In [ ]:
!pip install pandarallel tqdm

Collecting pandarallel
  Downloading pandarallel-1.6.5.tar.gz (14 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (4.67.1)
Requirement already satisfied: dill>=0.3.1 in /usr/local/lib/python3.12/dist-packages (from pandarallel) (0.3.8)
Requirement already satisfied: pandas>=1 in /usr/local/lib/python3.12/dist-packages (from pandarallel) (2.2.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from pandarallel) (5.9.5)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=1->pandarallel) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1->pandarallel) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1->pandarallel) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1->pandarallel) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1->pandarallel) (1.17.0)
Building wheels for collected packages: pandarallel
  Building wheel for pandarallel (setup.py) ... done
  Created wheel for pandarallel: filename=pandarallel-1.6.5-py3-none-any.whl size=16674 sha256=fad2736eaff93b77ad04be572d1b3d0b878151867bcf7dfeeaa65d592b5a7b7f
  Stored in directory: /root/.cache/pip/wheels/46/f9/0d/40c9cd74a7cb8dc8fe57e8d6c3c19e2c730449c0d3f2bf66b5
Successfully built pandarallel
Installing collected packages: pandarallel
Successfully installed pandarallel-1.6.5

In [ ]:
from pandarallel import pandarallel
from tqdm import tqdm

# Initialize pandarallel
pandarallel.initialize()

# Combine the lemma datasets
combined_lemma_df = pd.concat([bangla_lem_df, banel_df]).drop_duplicates().set_index('Inflected_Word')

# Create a dictionary for faster lookups
lemma_dict = combined_lemma_df['Lemma'].to_dict()

# Function for lemmatization
def lemmatize_text(tokens):
    return [lemma_dict.get(token, token) for token in tokens]

# Apply lemmatization using pandarallel
train_1A_df['l_nr_text'] = train_1A_df['t_text'].parallel_apply(lemmatize_text)
dev_1A_df['l_nr_text'] = dev_1A_df['t_text'].parallel_apply(lemmatize_text)
dev_test_1A_df['l_nr_text'] = dev_test_1A_df['t_text'].parallel_apply(lemmatize_text)
test_1A_df['l_nr_text'] = test_1A_df['t_text'].parallel_apply(lemmatize_text)

train_1B_df['l_nr_text'] = train_1B_df['t_text'].parallel_apply(lemmatize_text)
dev_1B_df['l_nr_text'] = dev_1B_df['t_text'].parallel_apply(lemmatize_text)
dev_test_1B_df['l_nr_text'] = dev_test_1B_df['t_text'].parallel_apply(lemmatize_text)
test_1B_df['l_nr_text'] = test_1B_df['t_text'].parallel_apply(lemmatize_text)

train_1C_df['l_nr_text'] = train_1C_df['t_text'].parallel_apply(lemmatize_text)
dev_1C_df['l_nr_text'] = dev_1C_df['t_text'].parallel_apply(lemmatize_text)
dev_test_1C_df['l_nr_text'] = dev_test_1C_df['t_text'].parallel_apply(lemmatize_text)
test_1C_df['l_nr_text'] = test_1C_df['t_text'].parallel_apply(lemmatize_text)

print("Text columns lemmatized in all datasets.")

INFO: Pandarallel will run on 1 workers.
INFO: Pandarallel will use Memory file system to transfer data between the main process and workers.
Text columns lemmatized in all datasets.

## Stopword removal

In [ ]:
# Combine all stopword lists into a single set for faster lookups
combined_stopwords = set(stopwords_iso + stopwords_kaggle + stopwords_eftekhar + stopwords_ranks)

# Function to remove stopwords
def remove_stopwords(tokens):
    return [token for token in tokens if token not in combined_stopwords]

# Apply stopword removal to all relevant text columns
train_1A_df['sr_nr_text'] = train_1A_df['t_text'].parallel_apply(remove_stopwords)
dev_1A_df['sr_nr_text'] = dev_1A_df['t_text'].parallel_apply(remove_stopwords)
dev_test_1A_df['sr_nr_text'] = dev_test_1A_df['t_text'].parallel_apply(remove_stopwords)
test_1A_df['sr_nr_text'] = test_1A_df['t_text'].parallel_apply(remove_stopwords)

train_1B_df['sr_nr_text'] = train_1B_df['t_text'].parallel_apply(remove_stopwords)
dev_1B_df['sr_nr_text'] = dev_1B_df['t_text'].parallel_apply(remove_stopwords)
dev_test_1B_df['sr_nr_text'] = dev_test_1B_df['t_text'].parallel_apply(remove_stopwords)
test_1B_df['sr_nr_text'] = test_1B_df['t_text'].parallel_apply(remove_stopwords)

train_1C_df['sr_nr_text'] = train_1C_df['t_text'].parallel_apply(remove_stopwords)
dev_1C_df['sr_nr_text'] = dev_1C_df['t_text'].parallel_apply(remove_stopwords)
dev_test_1C_df['sr_nr_text'] = dev_test_1C_df['t_text'].parallel_apply(remove_stopwords)
test_1C_df['sr_nr_text'] = test_1C_df['t_text'].parallel_apply(remove_stopwords)

print("Stopwords removed from text columns in all datasets.")

Stopwords removed from text columns in all datasets.

In [ ]:
# Apply stopword removal to all relevant text columns
train_1A_df['sr_l_nr_text'] = train_1A_df['sr_nr_text'].parallel_apply(lemmatize_text).parallel_apply(remove_stopwords)
dev_1A_df['sr_l_nr_text'] = dev_1A_df['sr_nr_text'].parallel_apply(lemmatize_text).parallel_apply(remove_stopwords)
dev_test_1A_df['sr_l_nr_text'] = dev_test_1A_df['sr_nr_text'].parallel_apply(lemmatize_text).parallel_apply(remove_stopwords)
test_1A_df['sr_l_nr_text'] = test_1A_df['sr_nr_text'].parallel_apply(lemmatize_text).parallel_apply(remove_stopwords)

train_1B_df['sr_l_nr_text'] = train_1B_df['sr_nr_text'].parallel_apply(lemmatize_text).parallel_apply(remove_stopwords)
dev_1B_df['sr_l_nr_text'] = dev_1B_df['sr_nr_text'].parallel_apply(lemmatize_text).parallel_apply(remove_stopwords)
dev_test_1B_df['sr_l_nr_text'] = dev_test_1B_df['sr_nr_text'].parallel_apply(lemmatize_text).parallel_apply(remove_stopwords)
test_1B_df['sr_l_nr_text'] = test_1B_df['sr_nr_text'].parallel_apply(lemmatize_text).parallel_apply(remove_stopwords)

train_1C_df['sr_l_nr_text'] = train_1C_df['sr_nr_text'].parallel_apply(lemmatize_text).parallel_apply(remove_stopwords)
dev_1C_df['sr_l_nr_text'] = dev_1C_df['sr_nr_text'].parallel_apply(lemmatize_text).parallel_apply(remove_stopwords)
dev_test_1C_df['sr_l_nr_text'] = dev_test_1C_df['sr_nr_text'].parallel_apply(lemmatize_text).parallel_apply(remove_stopwords)
test_1C_df['sr_l_nr_text'] = test_1C_df['sr_nr_text'].parallel_apply(lemmatize_text).parallel_apply(remove_stopwords)

## Joining Tokens

In [ ]:
# Function to join tokens back into a string
def join_tokens(tokens):
    return " ".join(tokens)

# Apply joining tokens to all relevant text columns
train_1A_df['sr_l_nr_text'] = train_1A_df['sr_l_nr_text'].apply(join_tokens)
dev_1A_df['sr_l_nr_text'] = dev_1A_df['sr_l_nr_text'].apply(join_tokens)
dev_test_1A_df['sr_l_nr_text'] = dev_test_1A_df['sr_l_nr_text'].apply(join_tokens)
test_1A_df['sr_l_nr_text'] = test_1A_df['sr_l_nr_text'].apply(join_tokens)

train_1B_df['sr_l_nr_text'] = train_1B_df['sr_l_nr_text'].apply(join_tokens)
dev_1B_df['sr_l_nr_text'] = dev_1B_df['sr_l_nr_text'].apply(join_tokens)
dev_test_1B_df['sr_l_nr_text'] = dev_test_1B_df['sr_l_nr_text'].apply(join_tokens)
test_1B_df['sr_l_nr_text'] = test_1B_df['sr_l_nr_text'].apply(join_tokens)

train_1C_df['sr_l_nr_text'] = train_1C_df['sr_l_nr_text'].apply(join_tokens)
dev_1C_df['sr_l_nr_text'] = dev_1C_df['sr_l_nr_text'].apply(join_tokens)
dev_test_1C_df['sr_l_nr_text'] = dev_test_1C_df['sr_l_nr_text'].apply(join_tokens)
test_1C_df['sr_l_nr_text'] = test_1C_df['sr_l_nr_text'].apply(join_tokens)





train_1A_df['l_nr_text'] = train_1A_df['l_nr_text'].apply(join_tokens)
dev_1A_df['l_nr_text'] = dev_1A_df['l_nr_text'].apply(join_tokens)
dev_test_1A_df['l_nr_text'] = dev_test_1A_df['l_nr_text'].apply(join_tokens)
test_1A_df['l_nr_text'] = test_1A_df['l_nr_text'].apply(join_tokens)

train_1B_df['l_nr_text'] = train_1B_df['l_nr_text'].apply(join_tokens)
dev_1B_df['l_nr_text'] = dev_1B_df['l_nr_text'].apply(join_tokens)
dev_test_1B_df['l_nr_text'] = dev_test_1B_df['l_nr_text'].apply(join_tokens)
test_1B_df['l_nr_text'] = test_1B_df['l_nr_text'].apply(join_tokens)

train_1C_df['l_nr_text'] = train_1C_df['l_nr_text'].apply(join_tokens)
dev_1C_df['l_nr_text'] = dev_1C_df['l_nr_text'].apply(join_tokens)
dev_test_1C_df['l_nr_text'] = dev_test_1C_df['l_nr_text'].apply(join_tokens)
test_1C_df['l_nr_text'] = test_1C_df['l_nr_text'].apply(join_tokens)




train_1A_df['sr_nr_text'] = train_1A_df['sr_nr_text'].apply(join_tokens)
dev_1A_df['sr_nr_text'] = dev_1A_df['sr_nr_text'].apply(join_tokens)
dev_test_1A_df['sr_nr_text'] = dev_test_1A_df['sr_nr_text'].apply(join_tokens)
test_1A_df['sr_nr_text'] = test_1A_df['sr_nr_text'].apply(join_tokens)

train_1B_df['sr_nr_text'] = train_1B_df['sr_nr_text'].apply(join_tokens)
dev_1B_df['sr_nr_text'] = dev_1B_df['sr_nr_text'].apply(join_tokens)
dev_test_1B_df['sr_nr_text'] = dev_test_1B_df['sr_nr_text'].apply(join_tokens)
test_1B_df['sr_nr_text'] = test_1B_df['sr_nr_text'].apply(join_tokens)

train_1C_df['sr_nr_text'] = train_1C_df['sr_nr_text'].apply(join_tokens)
dev_1C_df['sr_nr_text'] = dev_1C_df['sr_nr_text'].apply(join_tokens)
dev_test_1C_df['sr_nr_text'] = dev_test_1C_df['sr_nr_text'].apply(join_tokens)
test_1C_df['sr_nr_text'] = test_1C_df['sr_nr_text'].apply(join_tokens)

print("Text columns joined back into strings in all datasets.")

Text columns joined back into strings in all datasets.

In [ ]:
# Drop the 't_text' column from all dataframes
train_1A_df = train_1A_df.drop('t_text', axis=1)
dev_1A_df = dev_1A_df.drop('t_text', axis=1)
dev_test_1A_df = dev_test_1A_df.drop('t_text', axis=1)
test_1A_df = test_1A_df.drop('t_text', axis=1)

train_1B_df = train_1B_df.drop('t_text', axis=1)
dev_1B_df = dev_1B_df.drop('t_text', axis=1)
dev_test_1B_df = dev_test_1B_df.drop('t_text', axis=1)
test_1B_df = test_1B_df.drop('t_text', axis=1)

train_1C_df = train_1C_df.drop('t_text', axis=1)
dev_1C_df = dev_1C_df.drop('t_text', axis=1)
dev_test_1C_df = dev_test_1C_df.drop('t_text', axis=1)
test_1C_df = test_1C_df.drop('t_text', axis=1)

print("Dropped 't_text' column from all dataframes.")

Dropped 't_text' column from all dataframes.

## Samples

In [ ]:
print("Train 1A samples:")
display(train_1A_df[['text', 'sr_l_nr_text']].head())

Train 1A samples:

,text,sr_l_nr_text
0,ধন্যবাদ বর্ডার গার্ড দেরকে এভাবে পাহারা দিতে হ...,ধন্যবাদ বর্ডার গার্ড দের এভাবে পাহারা ভয় চলা ...
1,ছোটবেলায় অনেক কষ্ট করে কিছু গালাগালি শিখছিলাম...,শিশু কষ্ট গালাগালি শেখা ভাবা প্রয়োগ আফসোস বন্...
2,অতিরিক্ত এ নিজেকে বাদুর বানাইয়া ফেলছেন রে,অতিরিক্ত বাদুর বানাইয়া ফেলা রে
3,চিন ভারত রাশিয়া এই তিন দেশ এক থাকলে বিশ্বকে শা...,চিন ভারত রাশিয়া শাসন
4,এটার বিচার কে করবেযে বিচার করবে সেই তো হলো এই ...,এটার বিচার করবেযে বিচার চোর গড ফাদার

In [ ]:
print("\nTest 1A samples:")
display(test_1A_df[['text', 'sr_l_nr_text']].head())

Test 1A samples:

,text,sr_l_nr_text
0,ইজরায়েলের বিচার হওয়া উচিৎ,ইজরায়েলে বিচার
1,শামীম ওসামা বিন হাসিনা,শামীম ওসামা বিন হাসিনা
2,হেন কাপ পুলিশের মারে অন্যরা তাহলে পলিশের কি হব...,হেন কাপ পুলিশ মারা পলিশের বিচার
3,আল্লাহ্ এসব জানোয়ারদের শেষ করে দাও,আল্লাহ এসব জানোয়ার দাওয়া
4,ইহুদির বাচ্চা ইহুদী ই হবে,ইহুদির বাচ্চা ইহুদী

In [ ]:
print("Random Train 1A samples:")
display(train_1A_df[['text', 'sr_l_nr_text']].sample(5))

Random Train 1A samples:

,text,sr_l_nr_text
10976,মার্কিনীদের প্রেসিডেন্ট হিসেবে ডোনাল্ড ট্রাম্প...,মার্কিনী প্রেসিডেন্ট হিসাব ডোনাল্ড ট্রাম্প উপয...
13220,ভারতের নাম নিয়ে সময়টিভির এত মাথাব্যাথা কেন,ভারত সময়টিভির মাথাব্যাথা
4958,আমাদের কিশোরগঞ্জের ময়মনসিংহ মানুষেরা অনেক সুন...,কিশোরগঞ্জ ময়মনসিংহ সুন্দর মন ছেলেবেলার কথা পড়...
6322,আল্লাহ তুমি বিশ্বের সবাইকে হেফাজত করো,আল্লাহ হেফাজত
34024,আল্লাহ একটু দয়া কর,আল্লাহ দয়া

In [ ]:
print("\nRandom Test 1A samples:")
display(test_1A_df[['text', 'sr_l_nr_text']].sample(5))

Random Test 1A samples:

,text,sr_l_nr_text
692,চোখ মুখের অবস্থা দেখে মনে হচ্ছে চুরি করে আসছে ...,চোখ চুরি পুলিশ ফেলা চিন্তা
8122,তোর হাতে একটা মুলা ধরায় বের করা উচিত,হাত মুলা
4029,ইরানের দিন ঘনিয়ে আসছেইরাক আফগানিস্তান লিবিয়া...,ইরান ঘটা আসছেইরাক আফগানিস্তান লিবিয়া ভিয়েতনা...
4162,ডোনাল্ড ট্রাম্প বিশাল উধার মনের মানুষ ছিলো যের...,ডোনাল্ড ট্রাম্প বিশাল উধার মন ছিলো যেরকম ছিলো ...
3584,বাসটার্ড ইতালি এম্বেসি ৫ মাস পাসপোর্ট আটকিয়ে র...,বাসটার্ড ইতালি এম্বেসি মাস পাসপোর্ট আটকিয়ে ভিসা

# Download All Files

In [ ]:
from google.colab import files

# Function to save and download dataframe
def save_and_download(df, filename):
    df.to_csv(filename, sep='\t', index=False)
    files.download(filename)

# Save and download each dataframe
save_and_download(train_1A_df, "blp25_hatespeech_subtask_1A_train.tsv")
save_and_download(dev_1A_df, "blp25_hatespeech_subtask_1A_dev.tsv")
save_and_download(dev_test_1A_df, "blp25_hatespeech_subtask_1A_dev_test.tsv")
save_and_download(test_1A_df, "blp25_hatespeech_subtask_1A_test.tsv")

save_and_download(train_1B_df, "blp25_hatespeech_subtask_1B_train.tsv")
save_and_download(dev_1B_df, "blp25_hatespeech_subtask_1B_dev.tsv")
save_and_download(dev_test_1B_df, "blp25_hatespeech_subtask_1B_dev_test.tsv")
save_and_download(test_1B_df, "blp25_hatespeech_subtask_1B_test.tsv")

save_and_download(train_1C_df, "blp25_hatespeech_subtask_1C_train.tsv")
save_and_download(dev_1C_df, "blp25_hatespeech_subtask_1C_dev.tsv")
save_and_download(dev_test_1C_df, "blp25_hatespeech_subtask_1C_dev_test.tsv")
save_and_download(test_1C_df, "blp25_hatespeech_subtask_1C_test.tsv")

print("Modified datasets saved and downloaded.")

Modified datasets saved and downloaded.